---
title: "DataPreparationPetronas"
author: "Ikmal"
date: "12/15/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Import dataset

```{r data preparation}
library(ggplot2)
library(CatEncoders)
df = read.csv("C:/Users/Ikmal Syafiq/Desktop/train.csv")
df
```

## data summary
```{r}
summary(df)
```

## Check missing values
You can also embed plots, for example:
```{r}
#number of missing values
lapply(df,function(x) { length(which(is.na(x)))})
```


```{r}
#percentage of missing values
lapply(df,function(x) { 100*(length(which(is.na(x)))/nrow(df))})
```
## Clean the data
```{r}
#drop variable through listwise deletion
df_new = na.omit(df)
#check new dataset with listwise deletion
lapply(df_new,function(x) { length(which(is.na(x)))})
```

```{r pressure, echo=FALSE}
# Label encoding
df_new$Gender = transform(LabelEncoder.fit(df_new$Gender), df_new$Gender)
df_new$Vehicle_Age = transform(LabelEncoder.fit(df_new$Vehicle_Age), df_new$Vehicle_Age)
df_new$Vehicle_Damage = transform(LabelEncoder.fit(df_new$Vehicle_Damage), df_new$Vehicle_Damage)
df_new$Age = transform(LabelEncoder.fit(df_new$Age), df_new$Age)
```

## Outlier detection
```{r}
boxplot(df_new[c('Age', 'Region_Code','Policy_Sales_Channel', 'Vintage')])
boxplot(df_new[c( 'Previously_Insured','Vehicle_Damage', 'Driving_License','Response')])
boxplot(df_new['Annual_Premium'])
```
```{r}
#remove outlier
#find Q1, Q3, and interquartile range for values in annual premium
Q1 <- quantile(df_new$Annual_Premium, .25)
Q3 <- quantile(df_new$Annual_Premium, .75)
IQR <- IQR(df_new$Annual_Premium)
#only keep rows in dataframe that have values within 1.5*IQR of Q1 and Q3
no_outliers <- subset(df_new, df_new$Annual_Premium> (Q1 - 1.5*IQR) & df_new$Annual_Premium< (Q3 + 1.5*IQR))
#view row and column count of new data frame
dim(no_outliers) 
dim(df_new)
dim(df_new[0])-dim(no_outliers[0])
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
